apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evalpulse
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: http

